#!/bin/bash

#
# Copyright (c) 2014      Samuel K. Gutierrez
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

declare -r CDOWN_S=10
declare -r REST_TIME_S=10
declare -r WORK_TIME_S=30

declare -a wos=( \
"jumping jacks" \
"wall sit" \
"push ups" \
"ab crunches" \
"step up onto chair" \
"squats" \
"triceps dip on chair" \
"plank" \
"high knees running in place" \
"lunge" \
"push up and rotation" \
"side plank left" \
"side plank right" \
)

function cdown()
{
    for i in `seq $CDOWN_S 0`; do
        say $i
        sleep 1
    done
}

for ix in ${!wos[*]}; do
    say "${wos[$ix]} in"
    cdown
    say "${wos[$ix]}"
    sleep $WORK_TIME_S
done
say "congrats! you have just completed the 7 minute workout."

exit 0
